### ISSUE TITLE
Patch version number is missing in Ubuntu package file name

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#42] opened 2020-07-29 09:48 UTC
Patch version number is missing in Ubuntu package file name. For example `https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-schema_1.12-start-linz~bionic_all.deb`

**Comment by strk** [comment] 2020-08-11 08:41
That's a tag which should teoretically NOT produce an upload. The problem is that the code that SKIPS the upload will always be committed *after* the tagged commit, which results in such upload. I think we should just manually delete those packages from packagecloud and be done. I'll proceed in this way.

**Comment by strk** [comment] 2020-08-11 08:43
I see the package was removed, so I'm closing this.

**Closed by strk** 2020-08-11 08:43 UTC
Labels: bug
